apiVersion: v1
kind: Service
metadata:
  name: k8-skaffold-srv
spec:
  type: NodePort
  selector:
    app: k8-skaffold
  ports:
    - name: k8-skaffold
      protocol: TCP
      port: 3000
      targetPort: 3000
